# Generated by Django 4.0.5 on 2022-06-12 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('criando_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='AutorLivro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criando_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor_id', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                ('livro_id', models.ForeignKey(db_column='livro_id', on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
            ],
            options={
                'verbose_name': 'AutorLivro',
                'verbose_name_plural': 'AutorLivro',
                'index_together': {('autor_id', 'livro_id')},
            },
        ),
    ]
