# Generated by Django 4.0.5 on 2022-06-12 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor'},
        ),
        migrations.AlterModelOptions(
            name='autorlivro',
            options={'verbose_name': 'Autor_Livro'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='criando_em',
        ),
        migrations.RemoveField(
            model_name='autorlivro',
            name='criando_em',
        ),
        migrations.AddField(
            model_name='autor',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 15, 49, 16, 494253), help_text='Data de criação do registro', verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='autorlivro',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 15, 49, 16, 494846), help_text='Data de criação do registro', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização do registro', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='autorlivro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização do registro', verbose_name='Atualizado em'),
        ),
    ]
