# Generated by Django 4.0.5 on 2022-06-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'verbose_name': 'Catalogo'},
        ),
        migrations.AlterModelOptions(
            name='catalogolivro',
            options={'verbose_name': 'Catalogo_Livro'},
        ),
        migrations.RenameField(
            model_name='catalogo',
            old_name='criando_em',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='catalogolivro',
            old_name='criando_em',
            new_name='criado_em',
        ),
    ]
