# Generated by Django 4.0.5 on 2022-06-12 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_atualizado_em_alter_livro_criado_em'),
        ('catalogos', '0002_alter_catalogo_options_alter_catalogolivro_options_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='catalogolivro',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização do registro', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 16, 13, 23, 41994), help_text='Data de criação do registro', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='catalogolivro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização do registro', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='catalogolivro',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 16, 13, 23, 42662), help_text='Data de criação do registro', verbose_name='Criado em'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogolivro',
            unique_together={('catalogo_id', 'livro_id')},
        ),
    ]
