# Generated by Django 4.0.5 on 2022-06-12 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField()),
                ('numero_pagina', models.IntegerField()),
                ('produtora', models.CharField(max_length=50)),
                ('criando_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'livros',
            },
        ),
    ]
