# Generated by Django 4.0.5 on 2022-06-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro'},
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='criando_em',
            new_name='criado_em',
        ),
    ]
