# Generated by Django 4.0.5 on 2022-06-12 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, help_text='Data da última atualização do registro', verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 12, 16, 13, 23, 38479), help_text='Data de criação do registro', verbose_name='Criado em'),
        ),
    ]
